### ISSUE TITLE
Provide example usage where one input parameter is used

### ISSUE THREAD

**Issue by jpconstantineau** [arduino/arduino-lint-action#4]
Issue: 
I am trying to setup the linter and for me to troubleshoot why the linter is having problems with my library, I would like the verbose option to be "true".  Unfortunately, the usage example does not provide any hints on how to change any of the options.  I tried googling how to add the verbose option without much success.

How to fix:
add one more usage example which sets one or more input options.

**Comment by per1234** [comment]
Fixed by https://github.com/arduino/arduino-lint-action/pull/5
