### ISSUE TITLE
Project not found

### ISSUE THREAD

**Issue by QuentinN42** [arduino/arduino-lint-action#6]
Hello,
I can't get rid of this error :
```
error: Error while finding projects: No projects found under /home/runner/work/CI-test/CI-test
Error: The process '/opt/hostedtoolcache/arduino-lint/1.0.0/x64/arduino-lint' failed with exit code 1
```
My project structure is :
```
.
├── README.md
├── src
│   └── ChatServer.ino
└── test
    └── test1.c
```
What is the assumed structure of projects ?

**Comment by per1234** [comment]
Hi @QuentinN42. You can learn about the correct structure for an Arduino sketch in the specification here:
https://arduino.github.io/arduino-cli/latest/sketch-specification/

**Comment by per1234** [comment]
I saw from https://github.com/Arduino-CI/arduino_ci/issues/295 that you are now able to use this action successfully with the specification compliant sketch format, so I'll go ahead and close this as resolved.
